### ISSUE TITLE
Duplicate template file names cause build error

### ISSUE THREAD

**Issue by matharden** [ampproject/ampstart#203]
If there are any duplicate file names across any template directories, a build error occurs as the temporary `.archive` directory uses a flat file structure.

https://travis-ci.org/ampproject/ampstart/builds/207479033

```

[19:37:17] Starting 'bundle'...
fs.js:894
  return binding.mkdir(pathModule._makeLong(path),
                 ^
Error: EEXIST: file already exists, mkdir '.archive/article/css'
    at Object.fs.mkdirSync (fs.js:894:18)
    at Object.done (/home/travis/build/ampproject/ampstart/tasks/bundle.js:57:10)
    at process.nextTick (/home/travis/build/ampproject/ampstart/node_modules/jsdom/lib/jsdom.js:320:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by camelburrito** [comment]
Fixed
