### ISSUE TITLE
bundle fails if images are two levels deep

### ISSUE THREAD

**Issue by gurmukhp** [ampproject/ampstart#502]
For the commerce template, we have images in multiple folders. Unfortunately because of this, the bundle task fails because it cannot find the files in the .archive folder.

https://github.com/ampproject/ampstart/pull/500/files#diff-6c7c80f6399ff9cfa78845d3dfefa2b3

```
start for /Users/gurmukh/Sites/github/ampstart-forked/dist/templates/e-commerce/product-details.amp.html
fs.js:907
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/img/e-commerce/product/light-large-1.jpg'
    at Object.fs.statSync (fs.js:907:18)
    at Object.statSync (/Users/gurmukh/Sites/github/ampstart-forked/node_modules/graceful-fs/polyfills.js:297:22)
    at Object.copySync (/Users/gurmukh/Sites/github/ampstart-forked/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:86)
    at /Users/gurmukh/Sites/github/ampstart-forked/tasks/bundle.js:67:12
    at Array.forEach (native)
    at Object.done (/Users/gurmukh/Sites/github/ampstart-forked/tasks/bundle.js:64:10)
    at process.nextTick (/Users/gurmukh/Sites/github/ampstart-forked/node_modules/jsdom/lib/jsdom.js:325:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by camelburrito** [comment]
the image paths have to be relative that solves this issue 

```json
      "colours": [{
          "name": "white",
          "thumb": {
            "image1": "../../img/e-commerce/product/light-small-1.jpg",
            "image2": "../../img/e-commerce/product/light-small-2.jpg",
            "image3": "../../img/e-commerce/product/light-small-3.jpg"
          },
          "large": {
            "image1": "../../img/e-commerce/product/light-large-1.jpg",
            "image2": "../../img/e-commerce/product/light-large-2.jpg",
            "image3": "../../img/e-commerce/product/light-large-3.jpg"
          }
        },{
          "name": "green",
          "thumb": {
            "image1": "../../img/e-commerce/product/dark-small-1.jpg",
            "image2": "../../img/e-commerce/product/dark-small-2.jpg",
            "image3": "../../img/e-commerce/product/dark-small-3.jpg"
          },
          "large": {
            "image1": "../../img/e-commerce/product/dark-large-1.jpg",
            "image2": "../../img/e-commerce/product/dark-large-2.jpg",
            "image3": "../../img/e-commerce/product/dark-large-3.jpg"
          }
        }
      ],
```
