### ISSUE TITLE
Explore method to download .zip versions of code

### ISSUE THREAD

**Issue by ericlindley-g** [ampproject/ampstart#71]

**Comment by camelburrito** [comment]
@erwinmombay use this bug for your current task.

**Comment by camelburrito** [comment]
```
00:25:58] Using gulpfile ~/ampstart/gulpfile.js
[00:25:58] Starting 'bundle'...
tar: Failed to open '../dist/archive/blog-photogallery.tar.gz'
child_process.js:531
    throw err;
    ^

Error: Command failed: cd .archive && tar -zcf ../dist/archive/blog-photogallery.tar.gz blog-photogallery/
tar: Failed to open '../dist/archive/blog-photogallery.tar.gz'

    at checkExecSyncError (child_process.js:488:13)
    at execSync (child_process.js:528:13)
    at Object.done (/Users/skrish/ampstart/tasks/bundle.js:42:5)
    at process.nextTick (/Users/skrish/ampstart/node_modules/jsdom/lib/jsdom.js:320:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
