### ISSUE TITLE
ampstart failing to run with Ubuntu 18.04

### ISSUE THREAD

**Issue by vtntimo** [ampproject/ampstart#817]
I am having trouble getting ampstart to run on Ubuntu 18.04. 

`npm i` runs and finishes without problems

`npm run watch` and `npm run build` both return the same error:

```
[21:05:19] Finished 'configurator:json' after 66 ms
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
  at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
  at onErrorNT (internal/child_process.js:379:16)
  at process._tickCallback (internal/process/next_tick.js:178:19)

Emitted 'error' event at:
  at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
  at onErrorNT (internal/child_process.js:379:16)
  at process._tickCallback (internal/process/next_tick.js:178:19)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kickstart@ build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kickstart@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

I've tried to run it with node versions 8.x, 9.x and 10.x, yet I still get the same error message. I also have the build-essential -package installed. I've gotten the ampstart-package to run on my macOS just fine, but this problem keeps persisting on Ubuntu.

**Comment by fstanis** [comment]
Perhaps Java is not installed? What's the output of `java -version`?

**Comment by vtntimo** [comment]
Doh.
